### ISSUE TITLE
Make an interface pls

### ISSUE THREAD

**Issue by ghost** [yarrm80s/orpheusdl#72]
a gui pls
edit: tks

**Comment by shahzoorali** [comment]
There is


https://github.com/liusitusha/OrpheusDL-GUI

**Comment by ghost** [comment]
Thank you.
________________________________
De : shahzoorali ***@***.***>
Envoyé : samedi, 26 octobre 2024 19:29
À : OrfiTeam/OrpheusDL ***@***.***>
Cc : Hypnos-CH ***@***.***>; Author ***@***.***>
Objet : Re: [OrfiTeam/OrpheusDL] Make an interface pls (Issue #72)


There is

https://github.com/liusitusha/OrpheusDL-GUI

**Comment by OrfiDev** [comment]
There is no official GUI planned for OrpheusDL. Also I've never seen that GUI someone else sent until now, and I can't recommend it since it's closed-source so it may be malicious (probably isn't, but you can't know and it being closed source is very suspicious, and breaks our license. It's also horrifically ugly.)

**Comment by shahzoorali** [comment]
>  It's also horrifically ugly.)

🤣 At ugly. I think I tried once when it was released. It worked as expected then.

**Comment by ghost** [comment]
https://www.mediafire.com/file/8ri9xtjmliaqdpe/Orpheusdl.zip/file
I found the missing files here, like settings and modules
a video on youtube explains a bit how to make it work o android
https://www.youtube.com/watch?v=-CBxPSFqJbY
I laughed too at ugly, i find it very classic
